name: Lint and test

on: push

jobs:
  LintAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node Environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm i
        npm i -g truffle
        npm i eslint
        npm i solhint
    - name: Run Ganache on Docker image
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli ganache-cli -f https://mainnet.infura.io/v3/937291f44721429e8355a40325549eef --unlock "0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95" --unlock "0x6B175474E89094C44Da98b954EedeAC495271d0F" --unlock "0x98CC3BD6Af1880fcfDa17ac477B2F612980e5e33" --unlock "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643" --unlock "0xa1a69453e299aa567214d0f2714084cb3b7e9ce1"
    - name: Lint
      run: npm run lint:nofix
    - name: Test
      run: truffle test --network mainlocal
      env:
        CI: true